#!/usr/bin/env python
from os import geteuid, system, popen
import sys, platform as p 
from time import sleep

if not geteuid() == 0:
    sys.exit("Please run as root!")

if p.system() == "Linux":
    system("apt-get update && apt-get install -y build-essential slowhttptest python-pip git")
    system("pip install python-nmap paramiko scapy")
    system("git clone https://github.com/ex0dus-0x/dedsploit /usr/share/dedsploit && chmod +x /usr/share/dedsploit/dedsploit && ln -s /usr/share/dedsploit/dedsploit /usr/bin/dedsploit")
    print "Complete!"
    

elif p.system() == "Mac":
    print "\033[1;33m[*] Installing... [*]\033[0m"
    sleep(2)
    brew = popen('if ! type "brew" > /dev/null; then echo "OS has brew"; else echo "No homebrew. Preparing to install..."; fi').read()
    if brew == "No homebrew. Preparing to install...":
        system('/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"')
    userAccount = popen("who am i | awk '{print $1}'").read()[:-1]
    system("sudo -H -u "+ userAccount + " bash -c 'brew update && brew install git slowhttptest'")
    system("easy_install pip")
    system("pip2.7 install python-nmap paramiko scapy")
    system("git clone https://github.com/ex0dus-0x/dedsploit /usr/share/dedsploit && chmod +x /usr/share/dedsploit/dedsploit && ln -s /usr/share/dedsploit/dedsploit /usr/bin/dedsploit")

else:
    sys.exit(1)


print "\033[1;32m[!] Finished Installing! Run 'dedsploit' to run program [!]\033[0m"
sys.exit(0)